application:
  id: "gtd-app-1-gtd"
  name: "gtd-app-1"
  description: "Example d-app with Typescript language"
  category: "d-app-auna-examples"
network:
  id: "gtd-test-network"
  name: "gtd-test-network"
  version: "1.0.0"
  action: "new-network"
  orderers:
    - nodes: 3
      org: "gtd-ordering"
      consensus: "etcdraft"
  channels:
    - channel: "main"
      orgs:
        - "gtd"
  organizations:
    - id: "gtd"
      hosted: true
  peers:
    - nodes: 2
      org: "gtd"
  chaincodes: []
smartcontracts: []
api:
  internal:
    - name: "api-int"
      protocol: "HTTP"
      port: "8080"
      host: "0.0.0.0"
      path: "/apis/internal/api-int"
      description: "Api Interna"
      runtime:
        image: "api-int-test1"
        type: "node"
        version: "14"
      env: []
      report: {}
      tasks: []
      cache: []
      mailer: {}
      metrics:
        enabled: true
        port: 8000
        endpoint: "/metrics"
      singleton: false
      permissions: []
  external:
    - name: "api-ext"
      protocol: "HTTP"
      port: "8081"
      host: "0.0.0.0"
      path: "/apis/external/api-ext"
      description: "Api externa"
      runtime:
        image: "api-ext-test"
        type: "node"
        version: "14"
      env: []
      report: {}
      tasks: []
      cache: []
      mailer: {}
      metrics:
        enabled: false
        port: 8000
        endpoint: "/metrics"
      singleton: false
      permissions: []
  both: []
cache: []
tasks: []
datasource: []
env: []
