---
application: 
  id: "primera-d-app-01" #Reemplaze por su identificador de ISV
  name: "primera-d-app-01"
  description: "Example d-app with Typescript language"
  category: "d-app-auna-examples"
network: 
  id: "primerared"
  name: "primerared"
  version: "1.0.0"
  action: "some-action"
  orderers: 
    - nodes: 3
      org: "bcs-ordering"
      consensus: etcdraft
  channels: 
  - channel: my-channel
    orgs:
    - "bcs"
  organizations:
  - id: bcs
    hosted: true
  peers: 
  - nodes: 2
    org: "bcs"
  chaincodes:
  - smartcontract: test-go
    channel: my-channel
    orgs:
    - bcs
smartcontracts:
- id: test-go
  endorsement: '{"identities":[{"role":{"name":"member","mspId":"xxxMSP"}}],"policy":{"signed-by":0}}' #en el objeto roles, campo mspId, cambiar "xxx" por identificador de isv, ejemplo: "mspId":"bcsMSP"
  metadapath:
  version: v1.0.0
  path: smartcontracts/test-go
  type: golang
api:
  internal:
    - name: "sample-internal-01" #Nombre de la api interna
      protocol: "HTTP" #Protocolo a utilizadar
      port: "4001"	
      host: "some.host"	
      path: "apis/internal/api-int"	
      description: "Internal Api example" #Descripción de la API interna
      runtime:	
        image: "example"	#Este campo permite indicar que se ocupe una imagen docker en vez de construir una a partír del código.
        type: "node-ts"	#Indicar el runtime
        version: "14" #Indica la versión del runtime
      env:
        - name: "SOME_VAR"
          value: "someValue"
      report: {}	
      tasks: []	
      cache: []	
      mailer: {}	
      metrics:	
        enabled: true	
        port: 8000	
        endpoint: "/metrics"	
      singleton: true	
      permissions: []
  external: # Las API externas se configuran de igual que las APIs internas
    - name: "sample-external-01"	
      protocol: "HTTP"	
      port: "4000"	#Puerto de escucha de la API externa
      host: "0.0.0.0"	
      path: "/apis/external/api-ext"	
      description: "External Api example"
      runtime:	
        image: "example"	
        type: "node"	
        version: "14"
      env:
        - name: "SOME_OTHER_VAR"
          value: "anotherValue"
      report: {}	
      tasks: []	
      cache: []	
      mailer: {}	
      metrics:	
        enabled: true	
        port: 8000	
        endpoint: "/metrics"	
      singleton: true	
      permissions: []
  both: []
cache: []
tasks: []
datasource: []
env: []
permissions: []